services:
  change-ownership:
    image: alpine
    user: root
    group_add:
      - "999"
    volumes:
      - badgr_server_api_sock:/badgr_server/sock
      - badgr_server_staticfiles:/badgr_server/staticfiles
      - badgr_server_mediafiles:/badgr_server/mediafiles
      - badgr_server_locales:/badgr_server/locales
    command: chown -R 999:999 /badgr_server/sock /badgr_server/staticfiles /badgr_server/mediafiles /badgr_server/locales

  # this container copies in the project code and runs the app with uwsgi
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod.api
    depends_on:
      db:
        condition: service_started
      memcached:
        condition: service_started
      redis:
        condition: service_started
      celery_worker:
        condition: service_started
    volumes:
      - badgr_server_api_sock:/badgr_server/sock
      - badgr_server_mediafiles:/badgr_server/mediafiles
      - badgr_server_staticfiles:/badgr_server/staticfiles
      - badgr_server_locales:/badgr_server/locales
    networks:
      - badgr
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Berlin

  # this container runs memcached
  memcached:
    image: "memcached:1.6.39-alpine"
    expose:
      - "11211"
    networks:
      - badgr
    command: ["memcached", "-m", "512", "-I", "10m", "-v"]
    environment:
      - TZ=Europe/Berlin

  # this container runs mysql (database)
  db:
    image: mysql:8.0.36
    volumes:
      - badgr_server_prod_db:/var/lib/mysql:rw
      - ./.docker/etc/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/mysql.cnf

    environment:
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - TZ=Europe/Berlin
    ulimits:
      # Needs to be set e.g. on Fedora, Arch, etc.
      # https://github.com/docker-library/mysql/issues/873#issuecomment-1909948195
      # https://github.com/ddev/ddev/issues/4862#issuecomment-1533141193
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity or LimitNOFILE=infinity (containerd)
        soft: 1048576
        hard: 1048576
    expose:
      - "3306"
    networks:
      - badgr

  # this container runs nginx (webserver) and uses the uwsgi app.sock file from prod_api via a volume
  nginx:
    image: nginx:1.26.2
    group_add:
      - "999"
    volumes:
      - ./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/config/nginx/sites-available:/etc/nginx/sites-available
      - badgr_server_api_sock:/sock
      - badgr_server_mediafiles:/mediafiles
      - badgr_server_staticfiles:/staticfiles
      - badgr_server_locales:/badgr_server/locales
    depends_on:
      - "api"
    networks:
      - badgr
    ports:
      - "8080:80"
    environment:
      - TZ=Europe/Berlin

  celery_worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod.api
    entrypoint: [] # Override the entrypoint from Dockerfile
    user: "999:999"
    command: >
      bash -c "PYTHONPATH=/badgr_server/apps celery -A mainsite worker --loglevel=info"
    volumes:
      - badgr_server_mediafiles:/badgr_server/mediafiles
      - badgr_server_locales:/badgr_server/locales
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - TZ=Europe/Berlin
    networks:
      - badgr
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - badgr
    environment:
      - TZ=Europe/Berlin

networks:
  badgr:
    driver: bridge

volumes:
  badgr_server_api_sock:
  badgr_server_mediafiles:
  badgr_server_staticfiles:
  badgr_server_locales:
  badgr_server_prod_db:
