# Generated by Django 5.2.8 on 2026-06-08 10:29

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0032_badgeuser_quota_release_informed'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='backup_codes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='mfa_reminder_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='totp_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='totp_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=None, null=True),
        ),
    ]
