name: 🏗️ Build and publish to Github Container Registry

on:
    push:
        branches: [main, production, develop]
        tags: ["v*.*.*"]
    pull_request:
        branches:
            - production
            - main
            - develop
    merge_group:
        branches:
            - production
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: ⬇️ Checkout repository
              uses: actions/checkout@v6

            - name: Checkout dashboard plugin
              uses: actions/checkout@v6
              with:
                repository: ${{ secrets.DASHBOARD_URL }}
                path: .tmp/dashboard
                token: ${{ secrets.PLUGINS_ACCESS_TOKEN }}

            - name: Checkout pdfeditor plugin
              uses: actions/checkout@v6
              with:
                repository: ${{ secrets.PDFEDITOR_URL }}
                path: .tmp/pdfeditor
                token: ${{ secrets.PLUGINS_ACCESS_TOKEN }}

            - name: Inject plugin apps
              run: |
                rm -rf apps/dashboard apps/pdfeditor
                cp -R .tmp/dashboard/dashboard apps/dashboard
                cp -R .tmp/pdfeditor/pdfeditor apps/pdfeditor

            - name: 🏄 Copy default env vars
              run: cp .docker/etc/settings_local.prod.py.example .docker/etc/settings_local.py

            - name: 🔑 Log in to the Container registry
              uses: docker/login-action@v4.0.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: 📋 Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v6.0.0
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  flavor: |
                      latest=auto
                      prefix=
                      suffix=

            - name: 🏗️ Build and push Docker image
              uses: docker/build-push-action@v7.0.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
